/** Failure and success handlers would be added **/
const GET_ALL_DATA_REQUEST = 'GET_ALL_DATA_REQUEST';
const GET_ALL_DATA_RESPONDED = 'GET_ALL_DATA_RESPONDED';
const ADD_ROW = 'ADD_ROW';
const SEND_EMAIL = 'SEND_EMAIL';

export {GET_ALL_DATA_REQUEST, GET_ALL_DATA_RESPONDED, ADD_ROW, SEND_EMAIL};
